version: "2.1"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: always
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 30
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "../Data/Redis:/Data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      retries: 30
  api:
    image: ubuntu:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: api
    ports:
      - 9000:9000
    volumes:
      - "../Data/API:/Storage"
      - "./Server/API:/Server"
      - "./Resources:/Resources"
    restart: always
    command: ["/Server/API", "-db", "/Resources/Database/KanjiKana.sqlite", "-amqp", "amqp://rabbitmq", "-redis", "redis", "-download", "/Storage", "-addr", "0.0.0.0", "-p", "9000"]
    